  version: 0.0
  os: linux
  files:
    - source: /
      destination: /var/www/
  hooks:
    BeforeInstall:
      - location: scripts/stop.sh
        timeout: 180

    AfterInstall:
      - location: scripts/deploy.sh
        timeout: 180